branches:
  - master

language: python
dist: xenial
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install coveralls -r requirements-dev.txt

script:
  - pytest --cov opentaxii

after_success:
  - coveralls
