db:
  image: postgres:9.4
  environment:
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
    POSTGRES_DB: opentaxii

opentaxii:
  image: intelworks/opentaxii
  environment:
    OPENTAXII_AUTH_SECRET: secret
    OPENTAXII_DOMAIN: 192.168.59.103:9000
    OPENTAXII_USER: user1
    OPENTAXII_PASS: pass1
    DATABASE_HOST: db
    DATABASE_NAME: opentaxii
    DATABASE_USER: user
    DATABASE_PASS: password
  volumes:
    - ./:/input:ro
  ports:
    - 9000:9000
  links:
    - db:db
